version: 2.1
orbs:
  aws-cli: circleci/aws-cli@2.0.6
commands:
  setup-aws-cli:
    steps:
      - awscli/install
      - run: aws --version
    
jobs:
  aws-cli-cred-setup:
    executor: aws-cli/default
    steps:
      - aws-cli/setup:
          aws-access-key-id: AWS_ACCESS_KEY_ID
          aws-secret-access-key: AWS_SECRET_ACCESS_KEY

  create-ec2-instance:
    docker:
      - image: cimg/base:stable # AWS CLI is pre-installed in this image
    steps:
      - checkout  # Checkout your source code

      - run:
          name: Get current branch name
          command: echo $CIRCLE_BRANCH

      - run:
          name: Create EC2 Instance on Specific Branches
          command: |
            # Define the branches where you want to create the EC2 instance
            ALLOWED_BRANCHES=("main" "dev" "qa" "stable")

            # Get the current branch name
            #CIRCLE_BRANCH="$(git rev-parse --abbrev-ref HEAD)"

            # Check if the current branch is in the list of allowed branches
            if [[ " ${ALLOWED_BRANCHES[@]} " =~ " $CIRCLE_BRANCH " ]]; then
              chmod +x ec2.sh && ./ec2.sh
              
            else
              echo "Skipping EC2 instance creation. Current branch ($CIRCLECI_BRANCH) is not in the list of allowed branches."
            fi

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - aws-cli-cred-setup:
          context: aws
      - create-ec2-instance:
          filters:
            branches:
              only:
                - main
                - dev
                - qa
                - stable
